# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58d95b5cc836d36cbf573ea3ab305eb1b5dcd83b3c627ba969f61ce526b10b87d9e6741b3f8ca23454c27d9348a159f5478e8d74b83b7b82c4b6101232e4b966

test:
  secret_key_base: 1b26f32e9848e9cad13aa1e16427f027da2e8818a3239c30e58b1cb47c045b3cd5bac3181acf0346dfce40bbd9827c3bd0fa13ecb46c6272085a83e80b38e36b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
